# Vertebrae Fracture Detection Dataset
path: /mnt/nfs1/home/yamamoto-hiroto/research/vertebrae_saka/Sakaguchi_file/YOLO_datasets/vertebrae_fracture
train: train/images
val: val/images
test: test/images

# Classes
nc: 1  # number of classes
names: ['fracture']  # class names
